#ifndef MANAS_RUN_CONTROL_H
#define MANAS_RUN_CONTROL_H

#define GPU_PLASMA_CODE

#define DEBUG_PLASMA

#define FORTRAN_NUMBER_OF_SMALL_STEPS 1

#define TOTAL_STEPS  5

#define FREE_RAM_MONITOR

#define TOLERANCE_DIGITS_AFTER_POINT 15

#define FORTRAN_NUMBER_OF_PARTICLES 320000

#define CURRENT_SUM_BUFFER_LENGTH 10

#define START_STEP_NUMBER 1

#define CHECK_ARRAY_OUTPUT

#define ABSOLUTE_TOLERANCE 1e-15

#define PARTICLE_TOLERANCE 1e-10

#define INITIAL_PARTICLE_TOLERANCE 1e-13

#define CPU_DEBUG_RUN

#define WRONG_CURRENTS_CHECK

#define FINAL_CONTROL_POINT_CHECK

#define PARTICLE_ATTRIBUTES 270

#define CHECK_CONTROL_MATRIX

#define PARTICLE_ARRAY_PORTION 10000

#endif
