#ifndef MANAS_RUN_CONTROL_H
#define MANAS_RUN_CONTROL_H

#define DEBUG_PLASMA
#define FORTRAN_NUMBER_OF_SMALL_STEPS 1
#define CURRENT_SUM_BUFFER_LENGTH 10
#define ABSOLUTE_TOLERANCE 1e-15
#define PARTICLE_TOLERANCE 1e-10

#define CHECK_ARRAY_OUTPUT

#endif
