#ifndef MANAS_RUN_CONTROL_H
#define MANAS_RUN_CONTROL_H

#define DEBUG_PLASMA

#define FORTRAN_NUMBER_OF_SMALL_STEPS 1

#define TOTAL_STEPS  5

#define FREE_RAM_MONITOR

#define CURRENT_SUM_BUFFER_LENGTH 10

#define START_STEP_NUMBER 1

#define CHECK_ARRAY_OUTPUT

#define ABSOLUTE_TOLERANCE 1e-15

#define PARTICLE_TOLERANCE 1e-10

#define CPU_DEBUG_RUN

#define PARTICLE_ATTRIBUTES 270

#endif
